import type { components } from './openapi.gen.d.ts'

export type Schemas = components['schemas']

export type ProductResponse = Schemas['ProductResponse']
export type ProductListResponse = Schemas['ProductListResponse']
export type ProductImageResponse = Schemas['ProductImageResponse']
export type CreateProductRequest = Schemas['CreateProductRequest']
export type UpdateProductRequest = Schemas['UpdateProductRequest']
export type UpdateStockRequest = Schemas['UpdateStockRequest']

export type CategoryResponse = Schemas['CategoryResponse']
export type CategorySummary = Schemas['CategorySummary']
export type CategorySummaryResponse = Schemas['CategorySummaryResponse']
export type CategoryWithChildren = Schemas['CategoryWithChildren']
export type CategoryTreeResponse = Schemas['CategoryTreeResponse']
export type CreateCategoryRequest = Schemas['CreateCategoryRequest']
export type UpdateCategoryRequest = Schemas['UpdateCategoryRequest']
export type ReorderCategoriesRequest = Schemas['ReorderCategoriesRequest']
export type CategoryOrder = Schemas['CategoryOrder']

export type RatingResponse = Schemas['RatingResponse']
export type RatingStatsResponse = Schemas['RatingStatsResponse']
export type CreateRatingRequest = Schemas['CreateRatingRequest']
export type UpdateRatingRequest = Schemas['UpdateRatingRequest']

export type AuthResponse = Schemas['AuthResponse']
export type TokenResponse = Schemas['TokenResponse']
export type UserResponse = Schemas['UserResponse']
export type LoginRequest = Schemas['LoginRequest']
export type RegisterRequest = Schemas['RegisterRequest']
export type RefreshTokenRequest = Schemas['RefreshTokenRequest']

export type CartResponse = Schemas['CartResponse']
export type CartItemResponse = Schemas['CartItemResponse']
export type CartSummaryResponse = Schemas['CartSummaryResponse']
export type AddToCartRequest = Schemas['AddToCartRequest']
export type UpdateCartItemRequest = Schemas['UpdateCartItemRequest']

export type CheckoutRequest = Schemas['CheckoutRequest']
export type CheckoutResponse = Schemas['CheckoutResponse']
export type CheckoutValidationResponse = Schemas['CheckoutValidationResponse']
export type CheckoutItemValidation = Schemas['CheckoutItemValidation']
export type AddressRequest = Schemas['AddressRequest']
export type AddressResponse = Schemas['AddressResponse']

export type OrderResponse = Schemas['OrderResponse']
export type OrderListResponse = Schemas['OrderListResponse']
export type OrderItemResponse = Schemas['OrderItemResponse']
export type OrderStatusHistoryResponse = Schemas['OrderStatusHistoryResponse']
export type OrderStatsResponse = Schemas['OrderStatsResponse']
export type UpdateOrderStatusRequest = Schemas['UpdateOrderStatusRequest']
export type CancelOrderRequest = Schemas['CancelOrderRequest']

export type RecipeResponse = Schemas['RecipeResponse']
export type RecipeListResponse = Schemas['RecipeListResponse']
export type RecipeStepResponse = Schemas['RecipeStepResponse']
export type RecipeIngredientResponse = Schemas['RecipeIngredientResponse']
export type RecipeImageResponse = Schemas['RecipeImageResponse']
export type NutritionResponse = Schemas['NutritionResponse']
export type TagResponse = Schemas['TagResponse']
export type CreateRecipeRequest = Schemas['CreateRecipeRequest']
export type UpdateRecipeRequest = Schemas['UpdateRecipeRequest']
export type RecipeStepRequest = Schemas['RecipeStepRequest']
export type RecipeIngredientRequest = Schemas['RecipeIngredientRequest']
